import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";
import { ArrowRight, Activity, Flame } from "lucide-react";
import { Link } from "wouter";
import { API_BASE_URL } from "../config";
export default function Tournaments() {
    const { data: tournaments, isLoading } = useQuery({
        queryKey: ["tournaments"],
        queryFn: async () => {
            const res = await axios.get(`${API_BASE_URL}/api/tournaments`);
            return res.data;
        }
    });
    return (_jsxs("div", { className: "p-8 lg:p-12 space-y-12 bg-[#0E0E10] min-h-screen text-white", children: [_jsxs("header", { className: "flex justify-between items-end", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-2 text-[#EF4444] text-[10px] font-black uppercase tracking-[0.3em]", children: [_jsx(Flame, { className: "h-4 w-4" }), " Global Arena"] }), _jsxs("h1", { className: "text-6xl md:text-8xl font-[900] italic tracking-tighter uppercase leading-[0.85]", children: ["Active ", _jsx("span", { className: "text-slate-800", children: "Leagues" })] })] }), _jsx(Link, { href: "/tournaments/new", className: "bg-[#EF4444] hover:bg-red-600 text-white px-8 py-4 rounded-2xl text-xs font-black uppercase tracking-widest shadow-[0_0_30px_rgba(239,68,68,0.2)] transition-all flex items-center gap-2", children: "Create Tournament" })] }), isLoading ? (_jsx("div", { className: "grid md:grid-cols-2 lg:grid-cols-3 gap-8", children: [1, 2, 3].map(i => (_jsx("div", { className: "h-[450px] bg-[#1C1C1E] rounded-[3rem] animate-pulse border border-[#2D2D30]" }, i))) })) : tournaments?.length > 0 ? (_jsx("div", { className: "grid md:grid-cols-2 lg:grid-cols-3 gap-8", children: tournaments.map((t) => (_jsx(TournamentCard, { tournament: t }, t._id))) })) : (_jsxs("div", { className: "bg-[#1C1C1E] border border-[#2D2D30] rounded-[3rem] p-24 text-center space-y-8 relative overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-[#EF4444]/5 opacity-50" }), _jsxs("div", { className: "relative z-10 space-y-6", children: [_jsx("div", { className: "w-20 h-20 bg-white/5 rounded-full flex items-center justify-center mx-auto border border-white/5", children: _jsx(Activity, { className: "h-10 w-10 text-slate-700" }) }), _jsx("h3", { className: "text-4xl font-black italic uppercase tracking-tighter", children: "The Arena is Empty" }), _jsx("p", { className: "text-slate-500 font-bold max-w-sm mx-auto uppercase text-xs tracking-widest", children: "No leagues have been authorized by the federation yet." })] })] }))] }));
}
function TournamentCard({ tournament }) {
    return (_jsxs("div", { className: "group relative", children: [_jsx("div", { className: "absolute -inset-0.5 bg-[#EF4444] rounded-[3rem] blur opacity-0 group-hover:opacity-20 transition duration-500" }), _jsx("div", { className: "relative bg-[#1C1C1E] border border-[#2D2D30] rounded-[3rem] overflow-hidden transition-all group-hover:translate-y-[-10px]", children: _jsxs("div", { className: "p-10 space-y-10", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsx("div", { className: "w-16 h-16 bg-[#EF4444]/10 rounded-2xl flex items-center justify-center text-3xl font-black text-[#EF4444] group-hover:bg-[#EF4444] group-hover:text-white transition-all", children: tournament.sportType[0] }), _jsx("div", { className: "bg-white/5 px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-widest text-slate-500 border border-white/5", children: tournament.type || 'League' })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h3", { className: "text-3xl font-[900] italic uppercase tracking-tighter leading-none group-hover:text-[#EF4444] transition-colors", children: tournament.name }), _jsxs("p", { className: "text-[10px] font-black uppercase tracking-[0.3em] text-slate-600 italic", children: [tournament.sportType, " Championship"] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4 py-8 border-y border-white/5", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[9px] font-black uppercase tracking-widest text-slate-700 mb-1", children: "Status" }), _jsx("p", { className: "text-xs font-black text-blue-500 uppercase italic tracking-tight", children: tournament.status })] }), _jsxs("div", { children: [_jsx("p", { className: "text-[9px] font-black uppercase tracking-widest text-slate-700 mb-1", children: "Roster" }), _jsxs("p", { className: "text-xs font-black text-white uppercase italic tracking-tight", children: [tournament.teamsCount || 0, " Teams"] })] })] }), _jsx(Link, { href: `/tournaments/${tournament._id}`, className: "block", children: _jsxs("button", { className: "w-full bg-[#EF4444]/10 hover:bg-[#EF4444] text-[#EF4444] hover:text-white border border-[#EF4444]/20 py-5 rounded-2xl text-[10px] font-black uppercase tracking-[0.3em] transition-all flex items-center justify-center gap-3", children: ["Enter Arena ", _jsx(ArrowRight, { className: "h-4 w-4" })] }) })] }) })] }));
}
